import { useState } from 'react';
import { calendar, type Driver, type Team } from '../lib/racingData';
import { GarageModal } from './GarageModal';
import { SeasonSummary } from './SeasonSummary';
import type { RaceHistoryItem } from '../lib/career';

type Props = { team: Team; driver: string; driverRating: number; racesCompleted: number; teamDrivers: string[]; gridDrivers: string[]; raceHistory: RaceHistoryItem[]; driverPoints: Record<string, number>; budget: number; pace: number; upgrades: string[]; market: Driver[]; round: number; contractYears: number; canSwitch: boolean; pitCrewLevel: number; onUpgrade: (name: string, cost: number) => void; onPitCrew: () => void; onHire: (driver: Driver) => void; onTrain: () => void; onDriver: (driver: string) => void; onWeekend: () => void; onSwitch: () => void };

export function TeamHQ(p: Props) {
  const [garage, setGarage] = useState(false);
  const [table, setTable] = useState(false);
  const [offer, setOffer] = useState<Driver | null>(null);
  const [salary, setSalary] = useState(0);
  const pitCost = Math.round(6 * 1.5 ** (p.pitCrewLevel - 1));
  const service = Math.max(2.3, 5 - (p.pitCrewLevel - 1) * .3);
  const validOffer = offer !== null && salary >= offer.salary * .85 && salary <= p.budget;

  return <section className="hq"><header className="hq-head"><div><p className="eyebrow">TEAM HQ · {p.contractYears} YEAR CONTRACT</p><h1>{p.team.name}</h1></div><div className="budget">€{p.budget}M <small>BUDGET</small></div></header><div className="stat-row"><span>CAR PACE <b>{p.pace}</b></span><span>DRIVER <b>{p.driverRating.toFixed(1)} / 100</b></span><span>ROUND <b>{p.round}/24</b></span></div><section className="driver-growth"><div><p className="panel-label">DRIVER DEVELOPMENT</p><b>{p.driver} · {p.driverRating.toFixed(1)}</b><small>+0.625 per race · {p.racesCompleted}/24</small></div><div className="rating-bar"><i style={{ width: `${p.driverRating}%` }} /></div></section><section className="pit-crew"><div><p className="panel-label">PIT CREW</p><b>LEVEL {p.pitCrewLevel}/10 · {service.toFixed(2)} SEC</b><small>Level 1 starts at 5.00 seconds.</small></div><button disabled={p.pitCrewLevel >= 10 || p.budget < pitCost} onClick={p.onPitCrew}>{p.pitCrewLevel === 10 ? 'MAXED' : `UPGRADE €${pitCost}M`}</button></section><section className="driver-select"><div><p className="panel-label">DRIVER FOR NEXT WEEKEND</p><b>Team mate gets a random result.</b></div>{p.teamDrivers.map((name) => <button className={name === p.driver ? 'selected' : ''} onClick={() => p.onDriver(name)} key={name}>{name}<small>{name === p.driver ? 'YOU PLAY' : 'RANDOM'}</small></button>)}</section><button className="championship-button" onClick={() => setTable(!table)}>VIEW SEASON</button>{table && <SeasonSummary drivers={p.gridDrivers} points={p.driverPoints} history={p.raceHistory} />}<div className="hq-grid"><div className="hq-panel"><p className="panel-label">CAR DEVELOPMENT</p><h2>GARAGE</h2><button className="action-button" onClick={() => setGarage(true)}>OPEN GARAGE →</button></div><div className="hq-panel"><p className="panel-label">DRIVER MARKET</p><h2>CONTRACTS</h2>{p.market.map((candidate) => <div className="shop-row" key={candidate.name}><div><b>{candidate.name}</b><small>ASKING PRICE: €{candidate.salary}M</small></div><button onClick={() => { setOffer(candidate); setSalary(candidate.salary); }}>NEGOTIATE</button></div>)}{offer && <div className="negotiation"><b>{offer.name}</b><small>ASKING PRICE €{offer.salary}M · YOUR OFFER</small><strong>€{salary}M</strong><input type="range" min="1" max={offer.salary + 12} value={salary} onChange={(event) => setSalary(Number(event.target.value))} /><button disabled={!validOffer} onClick={() => { if (validOffer) { p.onHire({ ...offer, salary }); setOffer(null); } }}>SEND OFFER</button></div>}<button onClick={p.onTrain}>TRAIN €4M</button></div></div><section className="next-race"><div><p className="panel-label">NEXT RACE</p><h2>{calendar[p.round - 1]} GRAND PRIX</h2></div><button className="action-button" onClick={p.onWeekend}>OPEN WEEKEND →</button></section>{garage && <GarageModal budget={p.budget} completed={p.upgrades} onClose={() => setGarage(false)} onUpgrade={p.onUpgrade} />}</section>;
}
