import { useState } from 'react';
import type { Team } from '../lib/racingData';

type Props = { teams: Team[]; selected: Team; year: number; onYear: (year: number) => void; onSelect: (team: Team) => void; onStart: (years: number, driverName: string | null, driverNumber: number) => void };

export function TeamPicker({ teams, selected, year, onYear, onSelect, onStart }: Props) {
  const [mode, setMode] = useState<'existing' | 'new'>('existing');
  const [teamName, setTeamName] = useState('Velocity Racing'); const [years, setYears] = useState(3);
  const [driverName, setDriverName] = useState('My Driver'); const [driverNumber, setDriverNumber] = useState(27);
  const [driverReady, setDriverReady] = useState(false);
  const [driverMode, setDriverMode] = useState<'custom' | 'existing'>('custom');
  const customTeam: Team = { name: teamName.trim() || 'Velocity Racing', color: '#8b4cff', pace: 66, budget: 38, driver: 'Rookie Driver', teammate: 'Team Mate' };
  const character = <section className="character-creator"><p className="panel-label">STEP 1 · CREATE YOUR DRIVER</p><label>DRIVER NAME<input disabled={driverReady} value={driverName} maxLength={20} onChange={(event) => setDriverName(event.target.value)} /></label><label>RACE NUMBER<input disabled={driverReady} type="number" min="1" max="99" value={driverNumber} onChange={(event) => setDriverNumber(Number(event.target.value))} /></label><div className="driver-preview"><b>#{driverNumber}</b><span>{driverName.trim() || 'My Driver'}</span></div><button className="driver-confirm" onClick={() => setDriverReady(!driverReady)}>{driverReady ? 'EDIT DRIVER' : 'CONFIRM DRIVER →'}</button></section>;
  const start = () => onStart(years, driverMode === 'custom' ? driverName.trim() || 'My Driver' : null, driverNumber);
  const canChooseTeam = driverMode === 'existing' || driverReady;
  return <section className="manager-wrap"><p className="eyebrow">NEW CAREER</p><h1 className="manager-title">BUILD YOUR<br /><em>F1 STORY</em></h1><label className="year-picker">STARTING SEASON <select value={year} onChange={(event) => onYear(Number(event.target.value))}><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option></select></label><div className="driver-mode"><button className={driverMode === 'custom' ? 'active' : ''} onClick={() => setDriverMode('custom')}>CREATE MY DRIVER</button><button className={driverMode === 'existing' ? 'active' : ''} onClick={() => setDriverMode('existing')}>PLAY EXISTING DRIVER</button></div>{driverMode === 'custom' && character}{canChooseTeam && <><p className="eyebrow team-step">STEP {driverMode === 'custom' ? '2' : '1'} · CHOOSE YOUR TEAM</p><div className="career-choice"><button className={mode === 'existing' ? 'active' : ''} onClick={() => setMode('existing')}>JOIN AN EXISTING TEAM</button><button className={mode === 'new' ? 'active' : ''} onClick={() => setMode('new')}>CREATE MY TEAM</button></div>{mode === 'existing' ? <><p className="manager-copy">{driverMode === 'custom' ? `Choose who signs ${driverName.trim() || 'your driver'}.` : 'Choose a team, then choose one of its existing drivers in the headquarters.'}</p><div className="team-cards">{teams.map((team) => <button className={selected.name === team.name ? 'team-card selected' : 'team-card'} onClick={() => onSelect(team)} key={team.name}><i style={{ background: team.color }} /><b>{team.name}</b><span>Pace {team.pace} · €{team.budget}M</span></button>)}</div><label className="contract-picker">MANAGER CONTRACT <select value={years} onChange={(event) => setYears(Number(event.target.value))}>{[1, 2, 3].map((value) => <option value={value} key={value}>{value} season{value > 1 ? 's' : ''}</option>)}</select></label><button className="action-button" onClick={start}>SIGN CONTRACT →</button></> : <div className="new-team-card"><p className="panel-label">NEW CONSTRUCTOR</p><h2>START FROM ZERO</h2><label>TEAM NAME<input value={teamName} maxLength={24} onChange={(event) => setTeamName(event.target.value)} /></label><button className="action-button" onClick={() => { onSelect(customTeam); start(); }}>ENTER F1 →</button></div>}</>}</section>;
}
